// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

// Structured body modifications applied atomically.
// Operations are applied in order: all replacements sequentially, then append.
// If any operation fails, the entire mutation fails (transactional).
type BodyModification struct {
	// Text replacements applied sequentially in array order.
	// Each old text must match exactly once at the time it's applied.
	Replace []*ReplaceOperation `json:"replace,omitempty"`
	// Text to append after all replacements.
	// Appended with blank line separator.
	Append *string `json:"append,omitempty"`
}

// Input for creating a new issue
type CreateIssueInput struct {
	// Issue title (required)
	Title string `json:"title"`
	// Issue type (defaults to 'task')
	Type *string `json:"type,omitempty"`
	// Status (defaults to 'todo')
	Status *string `json:"status,omitempty"`
	// Priority level (defaults to 'normal')
	Priority *string `json:"priority,omitempty"`
	// Tags for categorization
	Tags []string `json:"tags,omitempty"`
	// Markdown body content
	Body *string `json:"body,omitempty"`
	// Due date in YYYY-MM-DD format
	Due *string `json:"due,omitempty"`
	// Parent issue ID (validated against type hierarchy)
	Parent *string `json:"parent,omitempty"`
	// Issue IDs this issue is blocking
	Blocking []string `json:"blocking,omitempty"`
	// Issue IDs that are blocking this issue
	BlockedBy []string `json:"blockedBy,omitempty"`
}

// Filter options for querying issues
type IssueFilter struct {
	// Full-text search across slug, title, and body using Bleve query syntax.
	//
	// Examples:
	// - "login" - exact term match
	// - "login~" - fuzzy match (1 edit distance)
	// - "login~2" - fuzzy match (2 edit distance)
	// - "log*" - wildcard prefix
	// - "\"user login\"" - exact phrase
	// - "user AND login" - both terms required
	// - "user OR login" - either term
	// - "slug:auth" - search only slug field
	// - "title:login" - search only title field
	// - "body:auth" - search only body field
	Search *string `json:"search,omitempty"`
	// Include only issues with these statuses (OR logic)
	Status []string `json:"status,omitempty"`
	// Exclude issues with these statuses
	ExcludeStatus []string `json:"excludeStatus,omitempty"`
	// Include only issues with these types (OR logic)
	Type []string `json:"type,omitempty"`
	// Exclude issues with these types
	ExcludeType []string `json:"excludeType,omitempty"`
	// Include only issues with these priorities (OR logic)
	Priority []string `json:"priority,omitempty"`
	// Exclude issues with these priorities
	ExcludePriority []string `json:"excludePriority,omitempty"`
	// Include only issues with any of these tags (OR logic)
	Tags []string `json:"tags,omitempty"`
	// Exclude issues with any of these tags
	ExcludeTags []string `json:"excludeTags,omitempty"`
	// Include only issues with a parent
	HasParent *bool `json:"hasParent,omitempty"`
	// Include only issues with this specific parent ID
	ParentID *string `json:"parentId,omitempty"`
	// Include only issues that are blocking other issues
	HasBlocking *bool `json:"hasBlocking,omitempty"`
	// Include only issues that are blocking this specific issue ID
	BlockingID *string `json:"blockingId,omitempty"`
	// Include only issues that are blocked by others (via incoming blocking links or blocked_by field)
	IsBlocked *bool `json:"isBlocked,omitempty"`
	// Include only issues that have explicit blocked-by entries
	HasBlockedBy *bool `json:"hasBlockedBy,omitempty"`
	// Include only issues blocked by this specific issue ID (via blocked_by field)
	BlockedByID *string `json:"blockedById,omitempty"`
	// Exclude issues that have a parent
	NoParent *bool `json:"noParent,omitempty"`
	// Exclude issues that are blocking other issues
	NoBlocking *bool `json:"noBlocking,omitempty"`
	// Exclude issues that have explicit blocked-by entries
	NoBlockedBy *bool `json:"noBlockedBy,omitempty"`
	// Include only issues with sync data for this integration name
	HasSync *string `json:"hasSync,omitempty"`
	// Include only issues without sync data for this integration name
	NoSync *string `json:"noSync,omitempty"`
	// Include only issues where updatedAt > integration's synced_at (stale sync detection)
	SyncStale *string `json:"syncStale,omitempty"`
	// Include only issues updated at or after this timestamp
	ChangedSince *time.Time `json:"changedSince,omitempty"`
}

type Mutation struct {
}

type Query struct {
}

// A single text replacement operation.
type ReplaceOperation struct {
	// Text to find (must occur exactly once, cannot be empty)
	Old string `json:"old"`
	// Replacement text (can be empty to delete the matched text)
	New string `json:"new"`
}

// Sync metadata entry for a single integration
type SyncEntry struct {
	// Integration name (e.g., 'clickup', 'github')
	Name string `json:"name"`
	// Integration-specific data (arbitrary key-value pairs)
	Data map[string]any `json:"data"`
}

// Input for updating an existing issue
type UpdateIssueInput struct {
	// New title
	Title *string `json:"title,omitempty"`
	// New status
	Status *string `json:"status,omitempty"`
	// New type
	Type *string `json:"type,omitempty"`
	// New priority
	Priority *string `json:"priority,omitempty"`
	// Replace all tags (nil preserves existing, mutually exclusive with addTags/removeTags)
	Tags []string `json:"tags,omitempty"`
	// Add tags to existing list
	AddTags []string `json:"addTags,omitempty"`
	// Remove tags from existing list
	RemoveTags []string `json:"removeTags,omitempty"`
	// New body content (full replacement, mutually exclusive with bodyMod)
	Body *string `json:"body,omitempty"`
	// Structured body modifications (mutually exclusive with body)
	BodyMod *BodyModification `json:"bodyMod,omitempty"`
	// Due date in YYYY-MM-DD format (empty string to clear)
	Due *string `json:"due,omitempty"`
	// Set parent issue ID (null/empty to clear, validates type hierarchy)
	Parent *string `json:"parent,omitempty"`
	// Add issues to blocking list (validates cycles and existence)
	AddBlocking []string `json:"addBlocking,omitempty"`
	// Remove issues from blocking list
	RemoveBlocking []string `json:"removeBlocking,omitempty"`
	// Add issues to blocked-by list (validates cycles and existence)
	AddBlockedBy []string `json:"addBlockedBy,omitempty"`
	// Remove issues from blocked-by list
	RemoveBlockedBy []string `json:"removeBlockedBy,omitempty"`
	// ETag for optimistic concurrency control (optional)
	IfMatch *string `json:"ifMatch,omitempty"`
}
